name: Generate PDF from Markdown

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive texlive-xetex fonts-dejavu

      - name: Convert Markdown to PDF
        run: |
          mkdir output
          pandoc input.md -o output/ebook.pdf --toc --pdf-engine=xelatex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ebook
          path: output/ebook.pdf
